version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: CleanProject.Api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "9000:8080"
      - "9001:8081"
  
  cleanproject-db:
    image: postgres:16.2
    container_name: CleanProject.Db
    volumes:
      - ./.containers/cleanproject-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cleanproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    

  cleanproject-seq:
    image: datalust/seq:latest
    container_name: CleanProject.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"